In [31]:
import numpy as np

In [32]:
x_f=np.array([[167,51],[182,62],[176,69],[173,64],[172,65],[174,56],[169,58],[173,57],[170,55]])

In [33]:
x_f#question

array([[167,  51],
       [182,  62],
       [176,  69],
       [173,  64],
       [172,  65],
       [174,  56],
       [169,  58],
       [173,  57],
       [170,  55]])

In [34]:
y_t=np.array(["UW","N","N","N","N","UW","N","N","N"])#answer corresponding to the question

In [35]:
print("shape of x-f=",x_f.shape)
print("shape of y_t=",y_t.shape)

shape of x-f= (9, 2)
shape of y_t= (9,)


In [36]:
test=np.array([[170,57]])#to find out

In [38]:
from sklearn.metrics import euclidean_distances

In [39]:
dis=euclidean_distances(x_f,test)#(kisse,kiska)

In [40]:
dis

array([[ 6.70820393],
       [13.        ],
       [13.41640786],
       [ 7.61577311],
       [ 8.24621125],
       [ 4.12310563],
       [ 1.41421356],
       [ 3.        ],
       [ 2.        ]])

In [41]:
#location is s.no 6 .see label at sample no. 6

In [42]:
y_t[6]

'N'

In [43]:
#splitting the input and yout

In [44]:
xtrain=x_f[:7]
xtest=x_f[7:]
ytrain=y_t[:7]
ytest=y_t[7:]

In [45]:
#after calculating distance we take k=1 and we see just one sample

### By using sklearn

In [46]:
from sklearn.neighbors import KNeighborsClassifier

In [47]:
trainer=KNeighborsClassifier(n_neighbors=3)#by default its k=5

In [48]:
learner=trainer.fit(xtrain,ytrain)

In [49]:
learner.predict([[170,57]])#error because sample is 9 and k=10.It is a way of asking question

array(['UW'], dtype='<U2')

In [50]:
#prediction
ya=ytest#xtest
yp=learner.predict(xtest)

In [51]:
ya

array(['N', 'N'], dtype='<U2')

In [52]:
yp

array(['N', 'UW'], dtype='<U2')

In [53]:
from sklearn.metrics import accuracy_score

In [54]:
acc=accuracy_score(ya,yp)*100

In [55]:
acc

50.0

In [56]:
x=np.array([1,2])

## 

In [57]:
x*2

array([2, 4])

In [58]:
y=np.array([[2,2],[3,3]])

In [59]:
x*y#broadcasting

array([[2, 4],
       [3, 6]])

In [62]:
learner.predict([[170,57]])#beacause train data is 1D

array(['UW'], dtype='<U2')

In [63]:
learner.predict([[170,57]])#one dimension

array(['UW'], dtype='<U2')