In [135]:
from sklearn import datasets
import numpy as np

In [136]:
mydata=datasets.load_digits()

In [137]:
x_input=mydata.data
y_target=mydata.target

In [138]:
print("shape of x_input",x_input.shape)

shape of x_input (1797, 64)


In [139]:
print("shape of y_out",y_target.shape)

shape of y_out (1797,)


In [140]:
from sklearn.model_selection import train_test_split

In [141]:
xtrain,xtest,ytrain,ytest=train_test_split(x_input,y_target,test_size=.30,random_state=101)

In [142]:
print("Shape of xtrain is",xtrain.shape)
print("Shape of ytrain is",ytrain.shape)
print("Shape of xtest is",xtest.shape)
print("Shape of ytest is",xtest.shape)

Shape of xtrain is (1257, 64)
Shape of ytrain is (1257,)
Shape of xtest is (540, 64)
Shape of ytest is (540, 64)


In [143]:
from sklearn.svm import SVC

In [144]:
trainer=SVC(gamma=0.001)#gamma is learning rate whisch should be less
learner=trainer.fit(x_input,y_target)

In [145]:
#Testing
ya=ytest #xtest
yp=learner.predict(xtest)

In [146]:
from sklearn.metrics import accuracy_score,jaccard_similarity_score,confusion_matrix,classification_report

In [147]:
#acc=accuracy_score(ya,yp)
#jss=jaccard_similarity_score(ya,yp)
#cm=confusion_matrix(ya,yp)
#cr=classification_report(ya,yp)

In [148]:
#acc

In [149]:
#jss

In [150]:
#cm

In [151]:
#print(cr)

In [152]:
pwd

'C:\\Users\\HP'

In [153]:
from matplotlib import pyplot as plt
from scipy import misc

In [155]:
mytestdata=misc.imread(r"8.jpg")

C:\Users\HP\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: `imread` is deprecated!
`imread` is deprecated in SciPy 1.0.0, and will be removed in 1.2.0.
Use ``imageio.imread`` instead.
  """Entry point for launching an IPython kernel.


In [156]:
mytestdata#black=0

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       ...,

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]], dtype=uint8)

In [157]:
mytestdata.shape

(256, 256, 3)

In [158]:
#Resize into 8*8
image_resize=misc.imresize(mytestdata,(8,8))
print(image_resize.shape)

C:\Users\HP\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: DeprecationWarning: `imresize` is deprecated!
`imresize` is deprecated in SciPy 1.0.0, and will be removed in 1.3.0.
Use Pillow instead: ``numpy.array(Image.fromarray(arr).resize())``.
  


(8, 8, 3)


In [159]:
image_resize.dtype#unsigned int

dtype('uint8')

In [160]:
#converting into to float
image_float=image_resize.astype(mydata.images.dtype)
print(image_float.dtype)

float64


In [161]:
#Downscaling
image_scale=misc.bytescale(image_float,high=16,low=0)

C:\Users\HP\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: DeprecationWarning: `bytescale` is deprecated!
`bytescale` is deprecated in SciPy 1.0.0, and will be removed in 1.2.0.
  


In [162]:
image_scale

array([[[ 0,  0,  0],
        [ 0,  0,  0],
        [ 8,  8,  8],
        [13, 13, 13],
        [13, 13, 13],
        [ 2,  2,  2],
        [ 0,  0,  0],
        [ 0,  0,  0]],

       [[ 0,  0,  0],
        [ 3,  3,  3],
        [10, 10, 10],
        [ 0,  0,  0],
        [ 6,  6,  6],
        [ 7,  7,  7],
        [ 0,  0,  0],
        [ 0,  0,  0]],

       [[ 0,  0,  0],
        [ 3,  3,  3],
        [10, 10, 10],
        [ 0,  0,  0],
        [ 5,  5,  5],
        [ 7,  7,  7],
        [ 0,  0,  0],
        [ 0,  0,  0]],

       [[ 0,  0,  0],
        [ 0,  0,  0],
        [10, 10, 10],
        [10, 10, 10],
        [16, 16, 16],
        [ 5,  5,  5],
        [ 0,  0,  0],
        [ 0,  0,  0]],

       [[ 0,  0,  0],
        [ 0,  0,  0],
        [ 5,  5,  5],
        [15, 15, 15],
        [12, 12, 12],
        [11, 11, 11],
        [ 2,  2,  2],
        [ 0,  0,  0]],

       [[ 0,  0,  0],
        [ 4,  4,  4],
        [11, 11, 11],
        [ 2,  2,  2],
        [ 0,  0,  0],


In [163]:
image_scale_float=image_scale.astype(mydata.images.dtype)

In [164]:
image_scale_float.shape

(8, 8, 3)

In [165]:
image_scale_float

array([[[ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 8.,  8.,  8.],
        [13., 13., 13.],
        [13., 13., 13.],
        [ 2.,  2.,  2.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.]],

       [[ 0.,  0.,  0.],
        [ 3.,  3.,  3.],
        [10., 10., 10.],
        [ 0.,  0.,  0.],
        [ 6.,  6.,  6.],
        [ 7.,  7.,  7.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.]],

       [[ 0.,  0.,  0.],
        [ 3.,  3.,  3.],
        [10., 10., 10.],
        [ 0.,  0.,  0.],
        [ 5.,  5.,  5.],
        [ 7.,  7.,  7.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.]],

       [[ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [10., 10., 10.],
        [10., 10., 10.],
        [16., 16., 16.],
        [ 5.,  5.,  5.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.]],

       [[ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 5.,  5.,  5.],
        [15., 15., 15.],
        [12., 12., 12.],
        [11., 11., 11.],
        [ 2.,  2.,  2.],
        [ 0.,  0.

In [166]:
image_scale_float[0]

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 8.,  8.,  8.],
       [13., 13., 13.],
       [13., 13., 13.],
       [ 2.,  2.,  2.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [167]:
#Beautiful pattern
#add 0+0+0/3
#no loss of data and decreasing pixels

In [168]:
x_test_image=[]
for i in image_scale_float:
    for j in i:
        x_test_image.append(sum(j)/3.0)
len(x_test_image)

64

In [169]:
type(x_test_image)

list

In [170]:
Mytestimage=np.array(x_test_image)
type(Mytestimage)

numpy.ndarray

In [171]:
Mytestimage.shape

(64,)

In [172]:
Myreshapetestimage=Mytestimage.reshape(1,len(Mytestimage))
Myreshapetestimage.shape

(1, 64)

In [173]:
learner.predict(Myreshapetestimage)

array([8])