In [97]:
import pandas as pd

In [98]:
mydata=pd.read_excel(r"C:\Users\HP\Desktop\TECHNEX DATA\DataSets-master\winedata.xlsx")

In [99]:
mydata.head(1)

1.00     14.23    1.71     2.43     15.60    127.00   2.80     3.06     \
0        1     13.2     1.78     2.14     11.2      100     2.65     2.76   

   0.28     2.29     5.64     1.04     3.92     1065.00  
0     0.26     1.28     4.38     1.05      3.4     1050

In [100]:
names=["Cultivator","Alcohol","Malic_Acid","Alcalinityofash","Magnesium","Total_phenols","Flavanoids","Nonflavanoid_phenols","Proanthocyanins","Color_intensity","Hue","OD280/OD315ofdiluted_wines","Proline","Out"]

In [101]:
len(names)

14

In [102]:
mydata=pd.read_excel(r"C:\Users\HP\Desktop\TECHNEX DATA\DataSets-master\winedata.xlsx",names=names)

In [103]:
mydata.to_csv(r")

SyntaxError: EOL while scanning string literal (<ipython-input-103-e33675eb00cc>, line 1)

In [104]:
x=mydata.drop("Cultivator",axis=1)
y=mydata["Cultivator"]

In [105]:
import numpy as np

In [106]:
np.unique(y.values)

array([1, 2, 3], dtype=int64)

In [107]:
from sklearn.preprocessing import StandardScaler

In [108]:
print("mean of x",x.mean())
print("std of x ",x.values.std())

mean of x Alcohol                        12.993672
Malic_Acid                      2.339887
Alcalinityofash                 2.366158
Magnesium                      19.516949
Total_phenols                  99.587571
Flavanoids                      2.292260
Nonflavanoid_phenols            2.023446
Proanthocyanins                 0.362316
Color_intensity                 1.586949
Hue                             5.054802
OD280/OD315ofdiluted_wines      0.956983
Proline                         2.604294
Out                           745.096045
dtype: float64
std of x  215.30680616380351


In [109]:
xa=x.values
ya=y.values

In [110]:
scaler=StandardScaler()
xa=scaler.fit(xa).transform(xa)

In [111]:
print("mean of xa",round(xa.mean()))
print("Std of xa",xa.std())

mean of xa 0.0
Std of xa 1.0


In [112]:
from sklearn.model_selection import train_test_split

In [113]:
xtrain,xtest,ytrain,ytest=train_test_split(xa,ya,test_size=.30,random_state=101)

In [114]:
from sklearn.neural_network import MLPClassifier

In [115]:
xtrain

array([[-1.14525593, -0.1611677 , -0.7151169 , ..., -0.4244579 ,
         0.96102728, -1.1691207 ],
       [-0.77328768, -1.01230928,  0.70667226, ...,  1.0198265 ,
        -0.43278369, -0.21368624],
       [-1.45522948, -0.55538064, -1.77234474, ..., -0.07432835,
        -0.23366784, -1.05128378],
       ...,
       [-1.13285699, -1.08398436,  0.5243916 , ...,  1.54502083,
         0.16456387, -0.36655576],
       [ 0.9377663 , -0.54642125,  0.15983027, ...,  0.84476172,
         0.42056996,  1.83094348],
       [-1.46762842, -0.19700524,  1.36288264, ..., -0.03056216,
        -0.48967393, -0.38247966]])

In [255]:
trainer=MLPClassifier(hidden_layer_sizes=(13,13,13),max_iter=1000,activation='logistic')

In [256]:
learner=trainer.fit(xtrain,ytrain)

In [257]:
ya=ytest
yp=learner.predict(xtest)#again define ya here

In [258]:
#learner.coef_

In [262]:
from sklearn.metrics import accuracy_score,jaccard_similarity_score,confusion_matrix,classification_report

In [263]:
jss=jaccard_similarity_score(ya,yp)
acc=accuracy_score(ya,yp)
print("jss is",jss)
print("acc is ",acc)

jss is 0.9814814814814815
acc is  0.9814814814814815


In [264]:
cm=confusion_matrix(ya,yp)
cm

array([[19,  0,  0],
       [ 0, 20,  1],
       [ 0,  0, 14]], dtype=int64)

In [268]:
table=pd.crosstab(ya,yp,rownames=["ya"],colnames=["yp"])

In [269]:
table

yp   1   2   3
ya            
1   19   0   0
2    0  20   1
3    0   0  14

In [271]:
x=learner.coefs_
len(x)

4

In [273]:
len(x[0])

13

In [274]:
b=learner.intercepts_

In [275]:
len(b)

4

In [276]:
len(b[0])#13 nodes each having 1 bias and 1 weight

13